// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.consul.inputs;

import com.pulumi.consul.inputs.ConfigEntryServiceRouterRouteMatchHttpArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConfigEntryServiceRouterRouteMatchArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConfigEntryServiceRouterRouteMatchArgs Empty = new ConfigEntryServiceRouterRouteMatchArgs();

    /**
     * Specifies a set of HTTP criteria used to evaluate incoming L7 traffic for matches.
     * 
     */
    @Import(name="http")
    private @Nullable Output<ConfigEntryServiceRouterRouteMatchHttpArgs> http;

    /**
     * @return Specifies a set of HTTP criteria used to evaluate incoming L7 traffic for matches.
     * 
     */
    public Optional<Output<ConfigEntryServiceRouterRouteMatchHttpArgs>> http() {
        return Optional.ofNullable(this.http);
    }

    private ConfigEntryServiceRouterRouteMatchArgs() {}

    private ConfigEntryServiceRouterRouteMatchArgs(ConfigEntryServiceRouterRouteMatchArgs $) {
        this.http = $.http;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConfigEntryServiceRouterRouteMatchArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConfigEntryServiceRouterRouteMatchArgs $;

        public Builder() {
            $ = new ConfigEntryServiceRouterRouteMatchArgs();
        }

        public Builder(ConfigEntryServiceRouterRouteMatchArgs defaults) {
            $ = new ConfigEntryServiceRouterRouteMatchArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param http Specifies a set of HTTP criteria used to evaluate incoming L7 traffic for matches.
         * 
         * @return builder
         * 
         */
        public Builder http(@Nullable Output<ConfigEntryServiceRouterRouteMatchHttpArgs> http) {
            $.http = http;
            return this;
        }

        /**
         * @param http Specifies a set of HTTP criteria used to evaluate incoming L7 traffic for matches.
         * 
         * @return builder
         * 
         */
        public Builder http(ConfigEntryServiceRouterRouteMatchHttpArgs http) {
            return http(Output.of(http));
        }

        public ConfigEntryServiceRouterRouteMatchArgs build() {
            return $;
        }
    }

}
