// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.consul.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConfigEntryServiceRouterRouteMatchHttpHeaderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConfigEntryServiceRouterRouteMatchHttpHeaderArgs Empty = new ConfigEntryServiceRouterRouteMatchHttpHeaderArgs();

    /**
     * Specifies that a request matches when the header with the given name is this exact value.
     * 
     */
    @Import(name="exact")
    private @Nullable Output<String> exact;

    /**
     * @return Specifies that a request matches when the header with the given name is this exact value.
     * 
     */
    public Optional<Output<String>> exact() {
        return Optional.ofNullable(this.exact);
    }

    /**
     * Specifies that the logic for the HTTP header match should be inverted.
     * 
     */
    @Import(name="invert")
    private @Nullable Output<Boolean> invert;

    /**
     * @return Specifies that the logic for the HTTP header match should be inverted.
     * 
     */
    public Optional<Output<Boolean>> invert() {
        return Optional.ofNullable(this.invert);
    }

    /**
     * Specifies the name of the HTTP header to match.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Specifies the name of the HTTP header to match.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Specifies that a request matches when the header with the given name has this prefix.
     * 
     */
    @Import(name="prefix")
    private @Nullable Output<String> prefix;

    /**
     * @return Specifies that a request matches when the header with the given name has this prefix.
     * 
     */
    public Optional<Output<String>> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    /**
     * Specifies that a request matches when the value in the `name` argument is present anywhere in the HTTP header.
     * 
     */
    @Import(name="present")
    private @Nullable Output<Boolean> present;

    /**
     * @return Specifies that a request matches when the value in the `name` argument is present anywhere in the HTTP header.
     * 
     */
    public Optional<Output<Boolean>> present() {
        return Optional.ofNullable(this.present);
    }

    /**
     * Specifies that a request matches when the header with the given name matches this regular expression.
     * 
     */
    @Import(name="regex")
    private @Nullable Output<String> regex;

    /**
     * @return Specifies that a request matches when the header with the given name matches this regular expression.
     * 
     */
    public Optional<Output<String>> regex() {
        return Optional.ofNullable(this.regex);
    }

    /**
     * Specifies that a request matches when the header with the given name has this suffix.
     * 
     */
    @Import(name="suffix")
    private @Nullable Output<String> suffix;

    /**
     * @return Specifies that a request matches when the header with the given name has this suffix.
     * 
     */
    public Optional<Output<String>> suffix() {
        return Optional.ofNullable(this.suffix);
    }

    private ConfigEntryServiceRouterRouteMatchHttpHeaderArgs() {}

    private ConfigEntryServiceRouterRouteMatchHttpHeaderArgs(ConfigEntryServiceRouterRouteMatchHttpHeaderArgs $) {
        this.exact = $.exact;
        this.invert = $.invert;
        this.name = $.name;
        this.prefix = $.prefix;
        this.present = $.present;
        this.regex = $.regex;
        this.suffix = $.suffix;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConfigEntryServiceRouterRouteMatchHttpHeaderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConfigEntryServiceRouterRouteMatchHttpHeaderArgs $;

        public Builder() {
            $ = new ConfigEntryServiceRouterRouteMatchHttpHeaderArgs();
        }

        public Builder(ConfigEntryServiceRouterRouteMatchHttpHeaderArgs defaults) {
            $ = new ConfigEntryServiceRouterRouteMatchHttpHeaderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param exact Specifies that a request matches when the header with the given name is this exact value.
         * 
         * @return builder
         * 
         */
        public Builder exact(@Nullable Output<String> exact) {
            $.exact = exact;
            return this;
        }

        /**
         * @param exact Specifies that a request matches when the header with the given name is this exact value.
         * 
         * @return builder
         * 
         */
        public Builder exact(String exact) {
            return exact(Output.of(exact));
        }

        /**
         * @param invert Specifies that the logic for the HTTP header match should be inverted.
         * 
         * @return builder
         * 
         */
        public Builder invert(@Nullable Output<Boolean> invert) {
            $.invert = invert;
            return this;
        }

        /**
         * @param invert Specifies that the logic for the HTTP header match should be inverted.
         * 
         * @return builder
         * 
         */
        public Builder invert(Boolean invert) {
            return invert(Output.of(invert));
        }

        /**
         * @param name Specifies the name of the HTTP header to match.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Specifies the name of the HTTP header to match.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param prefix Specifies that a request matches when the header with the given name has this prefix.
         * 
         * @return builder
         * 
         */
        public Builder prefix(@Nullable Output<String> prefix) {
            $.prefix = prefix;
            return this;
        }

        /**
         * @param prefix Specifies that a request matches when the header with the given name has this prefix.
         * 
         * @return builder
         * 
         */
        public Builder prefix(String prefix) {
            return prefix(Output.of(prefix));
        }

        /**
         * @param present Specifies that a request matches when the value in the `name` argument is present anywhere in the HTTP header.
         * 
         * @return builder
         * 
         */
        public Builder present(@Nullable Output<Boolean> present) {
            $.present = present;
            return this;
        }

        /**
         * @param present Specifies that a request matches when the value in the `name` argument is present anywhere in the HTTP header.
         * 
         * @return builder
         * 
         */
        public Builder present(Boolean present) {
            return present(Output.of(present));
        }

        /**
         * @param regex Specifies that a request matches when the header with the given name matches this regular expression.
         * 
         * @return builder
         * 
         */
        public Builder regex(@Nullable Output<String> regex) {
            $.regex = regex;
            return this;
        }

        /**
         * @param regex Specifies that a request matches when the header with the given name matches this regular expression.
         * 
         * @return builder
         * 
         */
        public Builder regex(String regex) {
            return regex(Output.of(regex));
        }

        /**
         * @param suffix Specifies that a request matches when the header with the given name has this suffix.
         * 
         * @return builder
         * 
         */
        public Builder suffix(@Nullable Output<String> suffix) {
            $.suffix = suffix;
            return this;
        }

        /**
         * @param suffix Specifies that a request matches when the header with the given name has this suffix.
         * 
         * @return builder
         * 
         */
        public Builder suffix(String suffix) {
            return suffix(Output.of(suffix));
        }

        public ConfigEntryServiceRouterRouteMatchHttpHeaderArgs build() {
            return $;
        }
    }

}
