// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.consul.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAclAuthMethodPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAclAuthMethodPlainArgs Empty = new GetAclAuthMethodPlainArgs();

    /**
     * The name of the ACL Auth Method.
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name of the ACL Auth Method.
     * 
     */
    public String name() {
        return this.name;
    }

    /**
     * The namespace to lookup the auth method.
     * 
     */
    @Import(name="namespace")
    private @Nullable String namespace;

    /**
     * @return The namespace to lookup the auth method.
     * 
     */
    public Optional<String> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * The partition to lookup the auth method.
     * 
     */
    @Import(name="partition")
    private @Nullable String partition;

    /**
     * @return The partition to lookup the auth method.
     * 
     */
    public Optional<String> partition() {
        return Optional.ofNullable(this.partition);
    }

    private GetAclAuthMethodPlainArgs() {}

    private GetAclAuthMethodPlainArgs(GetAclAuthMethodPlainArgs $) {
        this.name = $.name;
        this.namespace = $.namespace;
        this.partition = $.partition;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAclAuthMethodPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAclAuthMethodPlainArgs $;

        public Builder() {
            $ = new GetAclAuthMethodPlainArgs();
        }

        public Builder(GetAclAuthMethodPlainArgs defaults) {
            $ = new GetAclAuthMethodPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the ACL Auth Method.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        /**
         * @param namespace The namespace to lookup the auth method.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable String namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param partition The partition to lookup the auth method.
         * 
         * @return builder
         * 
         */
        public Builder partition(@Nullable String partition) {
            $.partition = partition;
            return this;
        }

        public GetAclAuthMethodPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetAclAuthMethodPlainArgs", "name");
            }
            return $;
        }
    }

}
