// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul
{
    public static class GetAutopilotHealth
    {
        /// <summary>
        /// The `consul.getAutopilotHealth` data source returns
        /// [autopilot health information](https://www.consul.io/api/operator/autopilot.html#read-health)
        /// about the current Consul cluster.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Consul = Pulumi.Consul;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var read = Consul.GetAutopilotHealth.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["health"] = read.Apply(getAutopilotHealthResult =&gt; getAutopilotHealthResult.Healthy),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetAutopilotHealthResult> InvokeAsync(GetAutopilotHealthArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAutopilotHealthResult>("consul:index/getAutopilotHealth:getAutopilotHealth", args ?? new GetAutopilotHealthArgs(), options.WithDefaults());

        /// <summary>
        /// The `consul.getAutopilotHealth` data source returns
        /// [autopilot health information](https://www.consul.io/api/operator/autopilot.html#read-health)
        /// about the current Consul cluster.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Consul = Pulumi.Consul;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var read = Consul.GetAutopilotHealth.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["health"] = read.Apply(getAutopilotHealthResult =&gt; getAutopilotHealthResult.Healthy),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAutopilotHealthResult> Invoke(GetAutopilotHealthInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAutopilotHealthResult>("consul:index/getAutopilotHealth:getAutopilotHealth", args ?? new GetAutopilotHealthInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAutopilotHealthArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The datacenter to use. This overrides the agent's
        /// default datacenter and the datacenter in the provider setup.
        /// </summary>
        [Input("datacenter")]
        public string? Datacenter { get; set; }

        public GetAutopilotHealthArgs()
        {
        }
        public static new GetAutopilotHealthArgs Empty => new GetAutopilotHealthArgs();
    }

    public sealed class GetAutopilotHealthInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The datacenter to use. This overrides the agent's
        /// default datacenter and the datacenter in the provider setup.
        /// </summary>
        [Input("datacenter")]
        public Input<string>? Datacenter { get; set; }

        public GetAutopilotHealthInvokeArgs()
        {
        }
        public static new GetAutopilotHealthInvokeArgs Empty => new GetAutopilotHealthInvokeArgs();
    }


    [OutputType]
    public sealed class GetAutopilotHealthResult
    {
        public readonly string? Datacenter;
        /// <summary>
        /// The number of redundant healthy servers that could fail
        /// without causing an outage
        /// </summary>
        public readonly int FailureTolerance;
        /// <summary>
        /// Whether the server is healthy according to the current Autopilot
        /// configuration
        /// </summary>
        public readonly bool Healthy;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A list of server health information. See below for details on the
        /// available information.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAutopilotHealthServerResult> Servers;

        [OutputConstructor]
        private GetAutopilotHealthResult(
            string? datacenter,

            int failureTolerance,

            bool healthy,

            string id,

            ImmutableArray<Outputs.GetAutopilotHealthServerResult> servers)
        {
            Datacenter = datacenter;
            FailureTolerance = failureTolerance;
            Healthy = healthy;
            Id = id;
            Servers = servers;
        }
    }
}
