// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul
{
    public static class GetAclPolicy
    {
        /// <summary>
        /// The `consul..AclPolicy` data source returns the information related to a
        /// [Consul ACL Policy](https://www.consul.io/docs/acl/acl-system.html#acl-policies).
        /// 
        /// 
        /// {{% examples %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetAclPolicyResult> InvokeAsync(GetAclPolicyArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetAclPolicyResult>("consul:index/getAclPolicy:getAclPolicy", args ?? new GetAclPolicyArgs(), options.WithVersion());
    }


    public sealed class GetAclPolicyArgs : Pulumi.InvokeArgs
    {
        [Input("datacenters")]
        private List<string>? _datacenters;

        /// <summary>
        /// The datacenters associated with the ACL Policy.
        /// </summary>
        public List<string> Datacenters
        {
            get => _datacenters ?? (_datacenters = new List<string>());
            set => _datacenters = value;
        }

        /// <summary>
        /// The description of the ACL Policy.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The name of the ACL Policy.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The namespace to lookup the policy.
        /// </summary>
        [Input("namespace")]
        public string? Namespace { get; set; }

        /// <summary>
        /// The rules associated with the ACL Policy.
        /// </summary>
        [Input("rules")]
        public string? Rules { get; set; }

        public GetAclPolicyArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetAclPolicyResult
    {
        /// <summary>
        /// The datacenters associated with the ACL Policy.
        /// </summary>
        public readonly ImmutableArray<string> Datacenters;
        /// <summary>
        /// The description of the ACL Policy.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? Namespace;
        /// <summary>
        /// The rules associated with the ACL Policy.
        /// </summary>
        public readonly string? Rules;

        [OutputConstructor]
        private GetAclPolicyResult(
            ImmutableArray<string> datacenters,

            string? description,

            string id,

            string name,

            string? @namespace,

            string? rules)
        {
            Datacenters = datacenters;
            Description = description;
            Id = id;
            Name = name;
            Namespace = @namespace;
            Rules = rules;
        }
    }
}
