# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Mapping, Optional, Tuple, Union
from .. import _utilities, _tables

__all__ = [
    'address',
    'ca_file',
    'ca_path',
    'ca_pem',
    'cert_file',
    'cert_pem',
    'datacenter',
    'http_auth',
    'insecure_https',
    'key_file',
    'key_pem',
    'namespace',
    'scheme',
    'token',
]

__config__ = pulumi.Config('consul')

address = __config__.get('address') or (_utilities.get_env('CONSUL_ADDRESS', 'CONSUL_HTTP_ADDR') or 'localhost:8500')

ca_file = __config__.get('caFile') or _utilities.get_env('CONSUL_CA_FILE')

ca_path = __config__.get('caPath') or _utilities.get_env('CONSUL_CAPATH')

ca_pem = __config__.get('caPem')

cert_file = __config__.get('certFile') or _utilities.get_env('CONSUL_CERT_FILE')

cert_pem = __config__.get('certPem')

datacenter = __config__.get('datacenter')

http_auth = __config__.get('httpAuth') or _utilities.get_env('CONSUL_HTTP_AUTH')

insecure_https = __config__.get('insecureHttps')

key_file = __config__.get('keyFile') or _utilities.get_env('CONSUL_KEY_FILE')

key_pem = __config__.get('keyPem')

namespace = __config__.get('namespace')

scheme = __config__.get('scheme') or (_utilities.get_env('CONSUL_SCHEME', 'CONSUL_HTTP_SCHEME') or 'http')

token = __config__.get('token') or _utilities.get_env('CONSUL_TOKEN', 'CONSUL_HTTP_TOKEN')

