// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.consul;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class AclTokenPolicyAttachmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final AclTokenPolicyAttachmentArgs Empty = new AclTokenPolicyAttachmentArgs();

    /**
     * The name of the policy attached to the token.
     * 
     */
    @Import(name="policy", required=true)
    private Output<String> policy;

    /**
     * @return The name of the policy attached to the token.
     * 
     */
    public Output<String> policy() {
        return this.policy;
    }

    /**
     * The id of the token.
     * 
     */
    @Import(name="tokenId", required=true)
    private Output<String> tokenId;

    /**
     * @return The id of the token.
     * 
     */
    public Output<String> tokenId() {
        return this.tokenId;
    }

    private AclTokenPolicyAttachmentArgs() {}

    private AclTokenPolicyAttachmentArgs(AclTokenPolicyAttachmentArgs $) {
        this.policy = $.policy;
        this.tokenId = $.tokenId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AclTokenPolicyAttachmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AclTokenPolicyAttachmentArgs $;

        public Builder() {
            $ = new AclTokenPolicyAttachmentArgs();
        }

        public Builder(AclTokenPolicyAttachmentArgs defaults) {
            $ = new AclTokenPolicyAttachmentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param policy The name of the policy attached to the token.
         * 
         * @return builder
         * 
         */
        public Builder policy(Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy The name of the policy attached to the token.
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        /**
         * @param tokenId The id of the token.
         * 
         * @return builder
         * 
         */
        public Builder tokenId(Output<String> tokenId) {
            $.tokenId = tokenId;
            return this;
        }

        /**
         * @param tokenId The id of the token.
         * 
         * @return builder
         * 
         */
        public Builder tokenId(String tokenId) {
            return tokenId(Output.of(tokenId));
        }

        public AclTokenPolicyAttachmentArgs build() {
            if ($.policy == null) {
                throw new MissingRequiredPropertyException("AclTokenPolicyAttachmentArgs", "policy");
            }
            if ($.tokenId == null) {
                throw new MissingRequiredPropertyException("AclTokenPolicyAttachmentArgs", "tokenId");
            }
            return $;
        }
    }

}
