// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul.Outputs
{

    [OutputType]
    public sealed class ConfigEntryServiceDefaultsTransparentProxy
    {
        public readonly bool DialedDirectly;
        public readonly int OutboundListenerPort;

        [OutputConstructor]
        private ConfigEntryServiceDefaultsTransparentProxy(
            bool dialedDirectly,

            int outboundListenerPort)
        {
            DialedDirectly = dialedDirectly;
            OutboundListenerPort = outboundListenerPort;
        }
    }
}
