// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul.Outputs
{

    [OutputType]
    public sealed class ConfigEntryServiceResolverRedirect
    {
        /// <summary>
        /// Specifies the datacenter at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        public readonly string? Datacenter;
        /// <summary>
        /// Specifies the namespace at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        public readonly string? Namespace;
        /// <summary>
        /// Specifies the admin partition at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        public readonly string? Partition;
        /// <summary>
        /// Specifies the cluster with an active cluster peering connection at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        public readonly string? Peer;
        /// <summary>
        /// Specifies the sameness group at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        public readonly string? SamenessGroup;
        /// <summary>
        /// Specifies the name of a service at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        public readonly string? Service;
        /// <summary>
        /// Specifies the name of a subset of services at the redirect’s destination that resolves local upstream requests. If empty, the default subset is used. If specified, you must also specify at least one of the following in the same Redirect map: Service, Namespace, andDatacenter.
        /// </summary>
        public readonly string? ServiceSubset;

        [OutputConstructor]
        private ConfigEntryServiceResolverRedirect(
            string? datacenter,

            string? @namespace,

            string? partition,

            string? peer,

            string? samenessGroup,

            string? service,

            string? serviceSubset)
        {
            Datacenter = datacenter;
            Namespace = @namespace;
            Partition = partition;
            Peer = peer;
            SamenessGroup = samenessGroup;
            Service = service;
            ServiceSubset = serviceSubset;
        }
    }
}
