// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package consul

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Starting with Consul 1.5.0, the AclBindingRule resource can be used to
// managed Consul ACL binding rules.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"fmt"
//
// 	"github.com/pulumi/pulumi-consul/sdk/v2/go/consul"
// 	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		minikube, err := consul.NewAclAuthMethod(ctx, "minikube", &consul.AclAuthMethodArgs{
// 			Config: pulumi.StringMap{
// 				"CACert":            pulumi.String(fmt.Sprintf("%v%v%v", "-----BEGIN CERTIFICATE-----\n", "...-----END CERTIFICATE-----\n", "\n")),
// 				"Host":              pulumi.String("https://192.0.2.42:8443"),
// 				"ServiceAccountJWT": pulumi.String("eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9..."),
// 			},
// 			Description: pulumi.String("dev minikube cluster"),
// 			Type:        pulumi.String("kubernetes"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		_, err = consul.NewAclBindingRule(ctx, "test", &consul.AclBindingRuleArgs{
// 			AuthMethod:  minikube.Name,
// 			BindName:    pulumi.String("minikube"),
// 			BindType:    pulumi.String("service"),
// 			Description: pulumi.String("foobar"),
// 			Selector:    pulumi.String("serviceaccount.namespace==default"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
type AclBindingRule struct {
	pulumi.CustomResourceState

	// The name of the ACL auth method this rule apply.
	AuthMethod pulumi.StringOutput `pulumi:"authMethod"`
	// The name to bind to a token at login-time.
	BindName pulumi.StringOutput `pulumi:"bindName"`
	// Specifies the way the binding rule affects a token
	// created at login.
	BindType pulumi.StringOutput `pulumi:"bindType"`
	// A free form human readable description of the
	// binding rule.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The namespace to create the binding
	// rule within.
	Namespace pulumi.StringPtrOutput `pulumi:"namespace"`
	// The expression used to math this rule against valid
	// identities returned from an auth method validation.
	Selector pulumi.StringPtrOutput `pulumi:"selector"`
}

// NewAclBindingRule registers a new resource with the given unique name, arguments, and options.
func NewAclBindingRule(ctx *pulumi.Context,
	name string, args *AclBindingRuleArgs, opts ...pulumi.ResourceOption) (*AclBindingRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AuthMethod == nil {
		return nil, errors.New("invalid value for required argument 'AuthMethod'")
	}
	if args.BindName == nil {
		return nil, errors.New("invalid value for required argument 'BindName'")
	}
	if args.BindType == nil {
		return nil, errors.New("invalid value for required argument 'BindType'")
	}
	var resource AclBindingRule
	err := ctx.RegisterResource("consul:index/aclBindingRule:AclBindingRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAclBindingRule gets an existing AclBindingRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAclBindingRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AclBindingRuleState, opts ...pulumi.ResourceOption) (*AclBindingRule, error) {
	var resource AclBindingRule
	err := ctx.ReadResource("consul:index/aclBindingRule:AclBindingRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AclBindingRule resources.
type aclBindingRuleState struct {
	// The name of the ACL auth method this rule apply.
	AuthMethod *string `pulumi:"authMethod"`
	// The name to bind to a token at login-time.
	BindName *string `pulumi:"bindName"`
	// Specifies the way the binding rule affects a token
	// created at login.
	BindType *string `pulumi:"bindType"`
	// A free form human readable description of the
	// binding rule.
	Description *string `pulumi:"description"`
	// The namespace to create the binding
	// rule within.
	Namespace *string `pulumi:"namespace"`
	// The expression used to math this rule against valid
	// identities returned from an auth method validation.
	Selector *string `pulumi:"selector"`
}

type AclBindingRuleState struct {
	// The name of the ACL auth method this rule apply.
	AuthMethod pulumi.StringPtrInput
	// The name to bind to a token at login-time.
	BindName pulumi.StringPtrInput
	// Specifies the way the binding rule affects a token
	// created at login.
	BindType pulumi.StringPtrInput
	// A free form human readable description of the
	// binding rule.
	Description pulumi.StringPtrInput
	// The namespace to create the binding
	// rule within.
	Namespace pulumi.StringPtrInput
	// The expression used to math this rule against valid
	// identities returned from an auth method validation.
	Selector pulumi.StringPtrInput
}

func (AclBindingRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*aclBindingRuleState)(nil)).Elem()
}

type aclBindingRuleArgs struct {
	// The name of the ACL auth method this rule apply.
	AuthMethod string `pulumi:"authMethod"`
	// The name to bind to a token at login-time.
	BindName string `pulumi:"bindName"`
	// Specifies the way the binding rule affects a token
	// created at login.
	BindType string `pulumi:"bindType"`
	// A free form human readable description of the
	// binding rule.
	Description *string `pulumi:"description"`
	// The namespace to create the binding
	// rule within.
	Namespace *string `pulumi:"namespace"`
	// The expression used to math this rule against valid
	// identities returned from an auth method validation.
	Selector *string `pulumi:"selector"`
}

// The set of arguments for constructing a AclBindingRule resource.
type AclBindingRuleArgs struct {
	// The name of the ACL auth method this rule apply.
	AuthMethod pulumi.StringInput
	// The name to bind to a token at login-time.
	BindName pulumi.StringInput
	// Specifies the way the binding rule affects a token
	// created at login.
	BindType pulumi.StringInput
	// A free form human readable description of the
	// binding rule.
	Description pulumi.StringPtrInput
	// The namespace to create the binding
	// rule within.
	Namespace pulumi.StringPtrInput
	// The expression used to math this rule against valid
	// identities returned from an auth method validation.
	Selector pulumi.StringPtrInput
}

func (AclBindingRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*aclBindingRuleArgs)(nil)).Elem()
}

type AclBindingRuleInput interface {
	pulumi.Input

	ToAclBindingRuleOutput() AclBindingRuleOutput
	ToAclBindingRuleOutputWithContext(ctx context.Context) AclBindingRuleOutput
}

func (AclBindingRule) ElementType() reflect.Type {
	return reflect.TypeOf((*AclBindingRule)(nil)).Elem()
}

func (i AclBindingRule) ToAclBindingRuleOutput() AclBindingRuleOutput {
	return i.ToAclBindingRuleOutputWithContext(context.Background())
}

func (i AclBindingRule) ToAclBindingRuleOutputWithContext(ctx context.Context) AclBindingRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AclBindingRuleOutput)
}

type AclBindingRuleOutput struct {
	*pulumi.OutputState
}

func (AclBindingRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AclBindingRuleOutput)(nil)).Elem()
}

func (o AclBindingRuleOutput) ToAclBindingRuleOutput() AclBindingRuleOutput {
	return o
}

func (o AclBindingRuleOutput) ToAclBindingRuleOutputWithContext(ctx context.Context) AclBindingRuleOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(AclBindingRuleOutput{})
}
