// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package consul

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetAclTokenSecretId(ctx *pulumi.Context, args *GetAclTokenSecretIdArgs, opts ...pulumi.InvokeOption) (*GetAclTokenSecretIdResult, error) {
	var rv GetAclTokenSecretIdResult
	err := ctx.Invoke("consul:index/getAclTokenSecretId:getAclTokenSecretId", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAclTokenSecretId.
type GetAclTokenSecretIdArgs struct {
	// The accessor ID of the ACL token.
	AccessorId string  `pulumi:"accessorId"`
	PgpKey     *string `pulumi:"pgpKey"`
}

// A collection of values returned by getAclTokenSecretId.
type GetAclTokenSecretIdResult struct {
	AccessorId        string `pulumi:"accessorId"`
	EncryptedSecretId string `pulumi:"encryptedSecretId"`
	// id is the provider-assigned unique ID for this managed resource.
	Id     string  `pulumi:"id"`
	PgpKey *string `pulumi:"pgpKey"`
	// The secret ID of the ACL token if `gpgKey` has not been set.
	SecretId string `pulumi:"secretId"`
}
