// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package consul

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// > This content is derived from https://github.com/terraform-providers/terraform-provider-consul/blob/master/website/docs/d/acl_token_secret_id.html.markdown.
func LookupAclTokenSecretId(ctx *pulumi.Context, args *GetAclTokenSecretIdArgs) (*GetAclTokenSecretIdResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["accessorId"] = args.AccessorId
		inputs["pgpKey"] = args.PgpKey
	}
	outputs, err := ctx.Invoke("consul:index/getAclTokenSecretId:getAclTokenSecretId", inputs)
	if err != nil {
		return nil, err
	}
	return &GetAclTokenSecretIdResult{
		AccessorId: outputs["accessorId"],
		EncryptedSecretId: outputs["encryptedSecretId"],
		PgpKey: outputs["pgpKey"],
		SecretId: outputs["secretId"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getAclTokenSecretId.
type GetAclTokenSecretIdArgs struct {
	// The accessor ID of the ACL token.
	AccessorId interface{}
	PgpKey interface{}
}

// A collection of values returned by getAclTokenSecretId.
type GetAclTokenSecretIdResult struct {
	AccessorId interface{}
	EncryptedSecretId interface{}
	PgpKey interface{}
	// The secret ID of the ACL token if `gpgKey` has not been set.
	SecretId interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
