// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.consul.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PreparedQueryDns {
    /**
     * @return The TTL to send when returning DNS results.
     * 
     */
    private @Nullable String ttl;

    private PreparedQueryDns() {}
    /**
     * @return The TTL to send when returning DNS results.
     * 
     */
    public Optional<String> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PreparedQueryDns defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String ttl;
        public Builder() {}
        public Builder(PreparedQueryDns defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ttl = defaults.ttl;
        }

        @CustomType.Setter
        public Builder ttl(@Nullable String ttl) {
            this.ttl = ttl;
            return this;
        }
        public PreparedQueryDns build() {
            final var o = new PreparedQueryDns();
            o.ttl = ttl;
            return o;
        }
    }
}
