// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul.Inputs
{

    public sealed class AclRoleTemplatedPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("datacenters")]
        private InputList<string>? _datacenters;

        /// <summary>
        /// Specifies the datacenters the effective policy is valid within.
        /// </summary>
        public InputList<string> Datacenters
        {
            get => _datacenters ?? (_datacenters = new InputList<string>());
            set => _datacenters = value;
        }

        /// <summary>
        /// The name of the templated policies.
        /// </summary>
        [Input("templateName", required: true)]
        public Input<string> TemplateName { get; set; } = null!;

        /// <summary>
        /// The templated policy variables.
        /// </summary>
        [Input("templateVariables")]
        public Input<Inputs.AclRoleTemplatedPolicyTemplateVariablesGetArgs>? TemplateVariables { get; set; }

        public AclRoleTemplatedPolicyGetArgs()
        {
        }
        public static new AclRoleTemplatedPolicyGetArgs Empty => new AclRoleTemplatedPolicyGetArgs();
    }
}
