// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul.Inputs
{

    public sealed class ConfigEntryServiceResolverRedirectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the datacenter at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        [Input("datacenter")]
        public Input<string>? Datacenter { get; set; }

        /// <summary>
        /// Specifies the namespace at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Specifies the admin partition at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        [Input("partition")]
        public Input<string>? Partition { get; set; }

        /// <summary>
        /// Specifies the cluster with an active cluster peering connection at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        [Input("peer")]
        public Input<string>? Peer { get; set; }

        /// <summary>
        /// Specifies the sameness group at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        [Input("samenessGroup")]
        public Input<string>? SamenessGroup { get; set; }

        /// <summary>
        /// Specifies the name of a service at the redirect’s destination that resolves local upstream requests.
        /// </summary>
        [Input("service")]
        public Input<string>? Service { get; set; }

        /// <summary>
        /// Specifies the name of a subset of services at the redirect’s destination that resolves local upstream requests. If empty, the default subset is used. If specified, you must also specify at least one of the following in the same Redirect map: Service, Namespace, andDatacenter.
        /// </summary>
        [Input("serviceSubset")]
        public Input<string>? ServiceSubset { get; set; }

        public ConfigEntryServiceResolverRedirectArgs()
        {
        }
        public static new ConfigEntryServiceResolverRedirectArgs Empty => new ConfigEntryServiceResolverRedirectArgs();
    }
}
