// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Consul.Inputs
{

    public sealed class ConfigEntryServiceIntentionsJwtProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the name of a JWT provider defined in the Name field of the jwt-provider configuration entry.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("verifyClaims")]
        private InputList<Inputs.ConfigEntryServiceIntentionsJwtProviderVerifyClaimArgs>? _verifyClaims;

        /// <summary>
        /// Specifies additional token information to verify beyond what is configured in the JWT provider configuration entry.
        /// </summary>
        public InputList<Inputs.ConfigEntryServiceIntentionsJwtProviderVerifyClaimArgs> VerifyClaims
        {
            get => _verifyClaims ?? (_verifyClaims = new InputList<Inputs.ConfigEntryServiceIntentionsJwtProviderVerifyClaimArgs>());
            set => _verifyClaims = value;
        }

        public ConfigEntryServiceIntentionsJwtProviderArgs()
        {
        }
        public static new ConfigEntryServiceIntentionsJwtProviderArgs Empty => new ConfigEntryServiceIntentionsJwtProviderArgs();
    }
}
