// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getKeyPrefix(args: GetKeyPrefixArgs, opts?: pulumi.InvokeOptions): Promise<GetKeyPrefixResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("consul:index/getKeyPrefix:getKeyPrefix", {
        "datacenter": args.datacenter,
        "namespace": args.namespace,
        "partition": args.partition,
        "pathPrefix": args.pathPrefix,
        "subkeyCollection": args.subkeyCollection,
        "token": args.token,
    }, opts);
}

/**
 * A collection of arguments for invoking getKeyPrefix.
 */
export interface GetKeyPrefixArgs {
    /**
     * The datacenter to use. This overrides the
     * agent's default datacenter and the datacenter in the provider setup.
     */
    datacenter?: string;
    /**
     * The namespace to lookup the keys within.
     */
    namespace?: string;
    /**
     * The namespace to lookup the keys within.
     */
    partition?: string;
    /**
     * Specifies the common prefix shared by all keys
     * that will be read by this data source instance. In most cases, this will
     * end with a slash to read a "folder" of subkeys.
     */
    pathPrefix: string;
    /**
     * Specifies a subkey in Consul to be read. Supported
     * values documented below. Multiple blocks supported.
     */
    subkeyCollection?: inputs.GetKeyPrefixSubkeyCollection[];
    /**
     * The ACL token to use. This overrides the
     * token that the agent provides by default.
     *
     * @deprecated The token argument has been deprecated and will be removed in a future release.
Please use the token argument in the provider configuration
     */
    token?: string;
}

/**
 * A collection of values returned by getKeyPrefix.
 */
export interface GetKeyPrefixResult {
    /**
     * The datacenter the keys are being read from.
     */
    readonly datacenter: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly namespace?: string;
    readonly partition?: string;
    /**
     * the common prefix shared by all keys being read.
     * * `var.<name>` - For each name given, the corresponding attribute
     * has the value of the key.
     */
    readonly pathPrefix: string;
    readonly subkeyCollection?: outputs.GetKeyPrefixSubkeyCollection[];
    /**
     * A map of the subkeys and values is set if no `subkey`
     * block is provided.
     */
    readonly subkeys: {[key: string]: string};
    /**
     * @deprecated The token argument has been deprecated and will be removed in a future release.
Please use the token argument in the provider configuration
     */
    readonly token?: string;
    readonly var: {[key: string]: string};
}
export function getKeyPrefixOutput(args: GetKeyPrefixOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetKeyPrefixResult> {
    return pulumi.output(args).apply((a: any) => getKeyPrefix(a, opts))
}

/**
 * A collection of arguments for invoking getKeyPrefix.
 */
export interface GetKeyPrefixOutputArgs {
    /**
     * The datacenter to use. This overrides the
     * agent's default datacenter and the datacenter in the provider setup.
     */
    datacenter?: pulumi.Input<string>;
    /**
     * The namespace to lookup the keys within.
     */
    namespace?: pulumi.Input<string>;
    /**
     * The namespace to lookup the keys within.
     */
    partition?: pulumi.Input<string>;
    /**
     * Specifies the common prefix shared by all keys
     * that will be read by this data source instance. In most cases, this will
     * end with a slash to read a "folder" of subkeys.
     */
    pathPrefix: pulumi.Input<string>;
    /**
     * Specifies a subkey in Consul to be read. Supported
     * values documented below. Multiple blocks supported.
     */
    subkeyCollection?: pulumi.Input<pulumi.Input<inputs.GetKeyPrefixSubkeyCollectionArgs>[]>;
    /**
     * The ACL token to use. This overrides the
     * token that the agent provides by default.
     *
     * @deprecated The token argument has been deprecated and will be removed in a future release.
Please use the token argument in the provider configuration
     */
    token?: pulumi.Input<string>;
}
